# Generated by Django 5.2.4 on 2025-07-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTuberInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('inquiry_type', models.CharField(choices=[('collaboration', 'Collaboration Request'), ('sponsorship', 'Sponsorship Opportunity'), ('interview', 'Interview Request'), ('event', 'Event Invitation'), ('general', 'General Inquiry'), ('business', 'Business Partnership')], default='general', max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('under_1k', 'Under $1,000'), ('1k_5k', '$1,000 - $5,000'), ('5k_10k', '$5,000 - $10,000'), ('10k_25k', '$10,000 - $25,000'), ('25k_50k', '$25,000 - $50,000'), ('over_50k', 'Over $50,000'), ('negotiable', 'Negotiable')], max_length=20)),
                ('project_timeline', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_audience', models.TextField(blank=True, help_text='Describe your target audience')),
                ('deliverables', models.TextField(blank=True, help_text='What deliverables do you expect?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'YouTuber Contacted'), ('in_discussion', 'In Discussion'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('youtuber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='youtubers.youtubers')),
            ],
            options={
                'verbose_name': 'YouTuber Inquiry',
                'verbose_name_plural': 'YouTuber Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
