# Generated by Django 5.2.4 on 2025-07-20 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtubers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='youtubers/%Y/%m/')),
                ('video_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('crew', models.CharField(choices=[('solo', 'Solo'), ('small', 'Small Team'), ('large', 'Large Team')], max_length=255)),
                ('camera_type', models.CharField(choices=[('canon', 'Canon'), ('nikon', 'Nikon'), ('sony', 'Sony'), ('red', 'RED'), ('fuji', 'Fujifilm'), ('panasonic', 'Panasonic'), ('other', 'Other')], max_length=255)),
                ('subs_count', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('code', 'Coding'), ('mobile_review', 'Mobile Review'), ('vlogs', 'Vlogs'), ('comedy', 'Comedy'), ('gaming', 'Gaming'), ('standup', 'Stand-up'), ('anime', 'Anime'), ('film_making', 'Film Making'), ('song', 'Music'), ('motivation', 'Motivation'), ('cooking', 'Cooking'), ('other', 'Other')], max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'YouTuber',
                'verbose_name_plural': 'YouTubers',
                'ordering': ['-created_date'],
            },
        ),
    ]
