# Generated by Django 5.2.4 on 2025-07-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubers',
            name='can_manage_inquiries',
            field=models.BooleanField(default=True, help_text='Whether creator can manage their own inquiries'),
        ),
        migrations.AddField(
            model_name='youtubers',
            name='creator_email',
            field=models.EmailField(blank=True, help_text='Email for creator dashboard login', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='youtubers',
            name='creator_username',
            field=models.CharField(blank=True, help_text='Username for creator dashboard', max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='youtubers',
            name='is_creator_verified',
            field=models.BooleanField(default=False, help_text='Whether creator account is verified'),
        ),
        migrations.AddField(
            model_name='youtubers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtuber_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
