# Generated by Django 5.2.4 on 2025-07-20 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('fb_handle', models.CharField(blank=True, max_length=255)),
                ('insta_handle', models.CharField(blank=True, max_length=255)),
                ('youtube_handle', models.CharField(blank=True, max_length=255)),
                ('twitter_handle', models.CharField(blank=True, max_length=255)),
                ('description_1', models.TextField(blank=True)),
                ('description_2', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
